/**
 * Citation metadata for the deterministic citation pipeline.
 *
 * Provides structured identifiers (canonical_ref, display_text, aliases)
 * that the platform's entity linker uses to match references in agent
 * responses to MCP tool results — without relying on LLM formatting.
 *
 * This is the UNIVERSAL template — works for all MCP types (law, sector,
 * agriculture, domain). Each MCP adapts the builder call to its own
 * field names.
 *
 * See: docs/guides/law-mcp-golden-standard.md Section 4.9c
 */

export interface CitationMetadata {
  canonical_ref: string;
  display_text: string;
  aliases?: string[];
  source_url?: string;
  lookup: {
    tool: string;
    args: Record<string, string>;
  };
}

/**
 * Build citation metadata for any retrieval tool response.
 *
 * @param canonicalRef  Primary reference the entity linker matches against
 *                      (e.g., "SFS 2018:218", "GDPR Article 33", "CVE-2024-1234")
 * @param displayText   How the reference appears in prose
 *                      (e.g., "34 § SFS 2018:218", "Article 33 of GDPR")
 * @param toolName      The MCP tool name (e.g., "get_provision", "get_article")
 * @param toolArgs      The tool arguments for verification lookup
 * @param sourceUrl     Official portal URL (optional)
 * @param aliases       Alternative names the LLM might use (optional)
 */
export function buildCitation(
  canonicalRef: string,
  displayText: string,
  toolName: string,
  toolArgs: Record<string, string>,
  sourceUrl?: string | null,
  aliases?: string[],
): CitationMetadata {
  return {
    canonical_ref: canonicalRef,
    display_text: displayText,
    ...(aliases && aliases.length > 0 && { aliases }),
    ...(sourceUrl && { source_url: sourceUrl }),
    lookup: {
      tool: toolName,
      args: toolArgs,
    },
  };
}

/**
 * Build citation metadata for a law MCP get_provision response.
 *
 * Handles Swedish-style YYYY:NNN statute IDs, chapter:section notation,
 * and short-name aliases. Other jurisdictions adapt field names.
 *
 * @param documentId     DB identifier (e.g., "2018:218", "LOV-2018-06-15-38")
 * @param documentTitle  Full title of the law
 * @param provisionRef   Provision reference (e.g., "34", "3:12")
 * @param inputDocId     The document_id argument as passed by the caller
 * @param inputSection   The section argument as passed by the caller
 * @param sourceUrl      Official portal URL (optional)
 * @param shortName      Short name / alias (optional)
 */
export function buildProvisionCitation(
  documentId: string,
  documentTitle: string,
  provisionRef: string,
  inputDocId: string,
  inputSection: string,
  sourceUrl?: string | null,
  shortName?: string | null,
): CitationMetadata {
  // Build canonical_ref — detect common statute ID formats
  let canonicalRef: string;
  if (documentId.match(/^\d{4}:\d+$/)) {
    // Swedish SFS format: "2018:218" → "SFS 2018:218"
    canonicalRef = `SFS ${documentId}`;
  } else if (documentId.match(/^LOV-\d{4}/)) {
    // Norwegian Lovdata format
    canonicalRef = documentId;
  } else {
    canonicalRef = documentTitle || documentId;
  }

  // Build display_text with provision reference
  let displayText: string;
  if (provisionRef && provisionRef.includes(':')) {
    // Chapter:section format (e.g., "3:12" → "3 kap. 12 §")
    const [ch, sec] = provisionRef.split(':');
    displayText = `${ch} kap. ${sec} § ${canonicalRef}`;
  } else if (provisionRef) {
    displayText = `§ ${provisionRef} ${canonicalRef}`;
  } else {
    displayText = canonicalRef;
  }

  // Build aliases
  const aliases: string[] = [];
  if (shortName) aliases.push(shortName);
  if (documentId !== canonicalRef) aliases.push(documentId);
  if (documentTitle && documentTitle !== canonicalRef) aliases.push(documentTitle);

  return {
    canonical_ref: canonicalRef,
    display_text: displayText,
    ...(aliases.length > 0 && { aliases }),
    ...(sourceUrl && { source_url: sourceUrl }),
    lookup: {
      tool: 'get_provision',
      args: { document_id: inputDocId, section: inputSection },
    },
  };
}

/**
 * Derive the DNSC source URL from a DNSC reference string.
 *
 * References are generated by ingestion from URL slugs (see scripts/ingest-dnsc.ts
 * generateReference()). We reverse-map the prefix to reconstruct the canonical
 * portal URL. The slug embedded in the reference is lowercase + hyphenated, which
 * matches the dnsc.ro URL path segment. Verified: dnsc.ro redirects to www.dnsc.ro.
 *
 * Pattern table (reference prefix → URL path):
 *   DNSC-DOC-<slug>    → /vezi/document/<slug>
 *   DNSC-ALERT-CVE-… → /citeste/alerta-cve-…
 *   DNSC-ALERT-<slug>  → /citeste/alerta-<slug>
 *   DNSC-WEEKLY-YYYY-MM-DD → /citeste/stirile-saptamanii-din-cybersecurity-DD-MM-YYYY
 *   DNSC-COMM-<slug>   → /citeste/comunicat-<slug>
 *   DNSC-ART-<slug>    → /citeste/<slug>
 */
export function dnscReferenceToSourceUrl(reference: string): string {
  const BASE = "https://www.dnsc.ro";
  const ref = reference.toUpperCase();

  if (ref.startsWith("DNSC-DOC-")) {
    const slug = reference.slice("DNSC-DOC-".length).toLowerCase();
    return `${BASE}/vezi/document/${slug}`;
  }

  if (ref.startsWith("DNSC-ALERT-CVE-")) {
    // DNSC-ALERT-CVE-YYYY-N → alerta-cve-YYYY-N
    const slug = reference.slice("DNSC-ALERT-".length).toLowerCase();
    return `${BASE}/citeste/alerta-${slug}`;
  }

  if (ref.startsWith("DNSC-ALERT-")) {
    const slug = reference.slice("DNSC-ALERT-".length).toLowerCase();
    return `${BASE}/citeste/alerta-${slug}`;
  }

  // DNSC-WEEKLY-YYYY-MM-DD — ingest stores date in the reference, reconstruct slug
  const weeklyDateMatch = reference.match(/^DNSC-WEEKLY-(\d{4})-(\d{2})-(\d{2})$/i);
  if (weeklyDateMatch) {
    const [, yyyy, mm, dd] = weeklyDateMatch;
    return `${BASE}/citeste/stirile-saptamanii-din-cybersecurity-${dd}-${mm}-${yyyy}`;
  }

  if (ref.startsWith("DNSC-WEEKLY-")) {
    const slug = reference.slice("DNSC-WEEKLY-".length).toLowerCase();
    return `${BASE}/citeste/${slug}`;
  }

  if (ref.startsWith("DNSC-COMM-")) {
    const slug = reference.slice("DNSC-COMM-".length).toLowerCase();
    return `${BASE}/citeste/comunicat-${slug}`;
  }

  if (ref.startsWith("DNSC-ART-")) {
    const slug = reference.slice("DNSC-ART-".length).toLowerCase();
    return `${BASE}/citeste/${slug}`;
  }

  // Unknown pattern — fall back to DNSC homepage
  return `${BASE}/`;
}

export interface ItemCitationFields {
  source: string;
  source_full_name: string;
  source_url: string;
  publisher: string;
  license: string;
  effective_date: string;
  mcp_tool: string;
}

/**
 * Build gateway-compatible citation fields for a DNSC search result row.
 *
 * The gateway's citation.py overlay picks up these fields from the MCP response
 * via existing_citation.get() priority. License code "Romanian-Legea-8-1996-Art-9"
 * is the only Romanian license present in infrastructure/attribution-licenses.json
 * (verified 2026-05-26); it is a GREEN-audited statutory carve-out applicable to
 * DNSC official texts (political/administrative category).
 *
 * @param item     Row from the guidance or advisories DB table
 * @param tool     MCP tool name calling this function
 */
export function buildItemCitation(
  item: { reference: string; title?: string; date?: string | null },
  tool: string,
): ItemCitationFields {
  return {
    source: item.reference,
    source_full_name: item.title ?? item.reference,
    source_url: dnscReferenceToSourceUrl(item.reference),
    publisher: "Directoratul Național de Securitate Cibernetică (DNSC)",
    license: "Romanian-Legea-8-1996-Art-9",
    effective_date: item.date ?? "",
    mcp_tool: tool,
  };
}

/**
 * Build citation for a sector regulator decision/regulation.
 *
 * @param reference      Decision/regulation reference (e.g., "FFFS 2024:1")
 * @param title          Full title
 * @param toolName       Tool name (e.g., "se_dp_get_decision")
 * @param toolArgs       Tool arguments
 * @param authority      Issuing authority (e.g., "IMY", "FI")
 * @param sourceUrl      Official URL (optional)
 */
export function buildRegulationCitation(
  reference: string,
  title: string,
  toolName: string,
  toolArgs: Record<string, string>,
  authority?: string | null,
  sourceUrl?: string | null,
): CitationMetadata {
  const canonicalRef = reference;
  const displayText = title || reference;
  const aliases: string[] = [];
  if (authority) aliases.push(`${authority}: ${reference}`);

  return {
    canonical_ref: canonicalRef,
    display_text: displayText,
    ...(aliases.length > 0 && { aliases }),
    ...(sourceUrl && { source_url: sourceUrl }),
    lookup: { tool: toolName, args: toolArgs },
  };
}
